language: c

sudo: required
dist: trusty

compiler:
        - clang
        - gcc

install:
        - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-add-repository -y ppa:h-rayflood/llvm
        - sudo apt-get update && sudo apt-get install -yy gcc-5 clang-3.6
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50
        - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.6 50
        - gcc --version
        - clang --version

script:
        - autoreconf -i && ./configure && make
